server:
  port: 8099  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  application:
    name: my-spring-ai
  ai:
    dashscope:
      api-key: sk-9c2a25a0ed034e84a3de3bbaad42a3aa
      chat:
        options:
          model: qwen3-max
      embedding:
        options:
          model: text-embedding-v4 #向量模型
          dimensions: 1024 #向量维度维度
    openai:
      api-key: sk-9c2a25a0ed034e84a3de3bbaad42a3aa
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        enabled: false
      embedding:
        enabled: false #关闭openai的embedding，否则会启动报错，容器中会存在2个EmbeddingModel
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG